python manage.py shell < ./data/add_to_model/nl_news.py
python manage.py shell < ./data/add_to_model/nl_web.py
python manage.py shell < ./data/add_to_model/de_news.py
python manage.py shell < ./data/add_to_model/de_web.py
python manage.py shell < ./data/add_to_model/it_news.py
python manage.py shell < ./data/add_to_model/it_web.py
python manage.py shell < ./data/add_to_model/fr_news.py
python manage.py shell < ./data/add_to_model/fr_web.py
python manage.py shell < ./data/add_to_model/en_news.py
python manage.py shell < ./data/add_to_model/en_web.py
python manage.py shell < ./data/add_to_model/es_news.py
python manage.py shell < ./data/add_to_model/es_web.py
