# Generated by Django 3.0.2 on 2020-03-14 12:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sentence_length', models.FloatField(default=0)),
                ('avg_word_length', models.FloatField(default=0)),
                ('language', models.TextField(choices=[('de', 'German'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French')])),
                ('content', models.CharField(max_length=255)),
                ('category', models.TextField(blank=True, choices=[('news', 'News'), ('web', 'Web'), ('kids', 'Kids')])),
            ],
        ),
    ]
