# Generated by Django 3.0.2 on 2020-03-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
