# Generated by Django 3.0.2 on 2020-03-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0002_sentence_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='reports',
            field=models.IntegerField(default=0),
        ),
    ]
