# Generated by Django 3.0.2 on 2020-03-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0004_sentence_partition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='partition',
        ),
    ]
