# Generated by Django 3.0.2 on 2020-03-17 19:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0005_remove_sentence_partition'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='ref_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
