# Generated by Django 3.0.2 on 2020-03-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0006_auto_20200317_1959'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sentence',
            index=models.Index(fields=['language'], name='sentences_s_languag_b5e396_idx'),
        ),
    ]
